name: Forever Mas
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83103
title: All things can be improved.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#484848'
    - '#7c7c7c'
    - '#a7a7a7'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
